# Generated by Django 3.0.7 on 2020-07-06 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_of_content', models.PositiveIntegerField()),
                ('media_type', models.CharField(blank=True, choices=[('gif', 'Gif'), ('img', 'Img'), ('video', 'Video'), ('code', 'Code'), ('text', 'Text')], max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('visual', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contents',
            },
        ),
        migrations.CreateModel(
            name='DataStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data_structures.Category')),
                ('contents', models.ManyToManyField(related_name='data_structure', to='data_structures.Content')),
            ],
            options={
                'verbose_name_plural': 'Data Structures',
            },
        ),
        migrations.CreateModel(
            name='AnimationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(default='rive-animation', max_length=50)),
                ('animation_file', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='animations', to='data_structures.Content')),
            ],
            options={
                'verbose_name_plural': 'Animations',
            },
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='algorithms', to='data_structures.Category')),
                ('contents', models.ManyToManyField(related_name='algorithm', to='data_structures.Content')),
                ('data_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='algorithms', to='data_structures.DataStructure')),
            ],
            options={
                'verbose_name_plural': 'Algorithms',
            },
        ),
    ]
