# Generated by Django 3.0.7 on 2020-07-09 21:57

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Algorithms',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name_plural': 'Data Structure Markdowns',
            },
        ),
        migrations.CreateModel(
            name='DataStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data_structures.Category')),
                ('markdown_content', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data_structures.Content')),
            ],
            options={
                'verbose_name_plural': 'Data Structures',
            },
        ),
        migrations.CreateModel(
            name='AnimationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(default='rive-animation', max_length=50)),
                ('animation_file', models.FileField(blank=True, null=True, upload_to='uploads')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='animations', to='data_structures.Algorithm')),
            ],
            options={
                'verbose_name_plural': 'Animations',
            },
        ),
        migrations.AddField(
            model_name='algorithm',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='algorithms', to='data_structures.Category'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='data_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='algorithms', to='data_structures.DataStructure'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='markdown_content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='data_structures.Content'),
        ),
    ]
