# Generated by Django 3.0.7 on 2020-07-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_structures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastructuremarkdown',
            options={'verbose_name_plural': 'Data Structure Markdowns'},
        ),
        migrations.AddField(
            model_name='datastructuremarkdown',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
