# Generated by Django 3.0.7 on 2020-07-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_structures', '0002_auto_20200709_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='datastructure',
            name='contents',
        ),
    ]
